### ISSUE TITLE
SPM Support without creating Objc Bridge Header

### ISSUE THREAD

**Issue by derekyu01** [Kount/kount-ios-swift-package#6]
Hi I was wondering how i could import the SDK using SPM without setting up an Objc Bridging Header. I have read the documentation and I was wondering if there was any alternatives, since this is causing issues in my projects build system.

**Comment by gjd-keynetics** [comment]
@derekyu01 @chernikovdaniil We don't actively track/support issues via github.  Please contact your Customer Success Manager or [support@kount.com](mailto:support@kount.com) for assistance in this matter.

**Comment by gjd-keynetics** [comment]
Closing this issue out as we recommended working with support directly.
